version: "3"
services:
    web:
        build: ./web
        restart: unless-stopped
        ports:
            - "8000:5000"
    remote:
        build: ./remote
        restart: unless-stopped
        ports:
            - "3112:8888"